### ISSUE TITLE
Gets all reads key error with dorado

### ISSUE THREAD

**Issue by kir1to455** [Psy-Fer/buttery-eel#31] opened 2024-01-04 11:38 UTC
Hi, I encountered an issue when using buttery-eel to baseclling with dorado-server.
![image](https://github.com/Psy-Fer/buttery-eel/assets/87375686/b0cd2c9b-f4ba-4ed0-aa7a-f2efe763199d)
I want to use Dorado to basecall the RNA methylation model.
Here is my code:
`
Slow5Dir="/public2/hjliang/ONT_data/slow5"
GuppyDir="/home/hjliang/software/ont-dorado-server/bin"
FastqDir="/public2/hjliang/ONT_data/fastq"
ModDir="/public2/hjliang/ONT_data/modkit"

buttery-eel -g ${GuppyDir} --config rna_rp4_130bps_sup.cfg --device cuda:0 -i ${Slow5Dir}/PAQ17395_hac.pass.blow5 --call_mods -o ${ModDir}/PAQ17395_hac.pass.m6A.mod.sam -q 7 --slow5_threads 40 --procs 40 --port 5000 --use_tcp
`
Here is the error I encountered:
![image](https://github.com/Psy-Fer/buttery-eel/assets/87375686/c86b78ef-c537-47ad-824a-573f92999c00)

I appreciate it if you could take a look.
Best wishes,
Kirito

**Comment by Psy-Fer** [comment] 2024-01-04 12:33
Hey,

I have yet to try the RNA mods methods. Ice got some m6a data we used to train something else with rna004. I'll give it a go on that and see what the problem is. I'll get back to you soon.

Cheers,
James

**Comment by Psy-Fer** [comment] 2024-01-15 09:23
Hey, Just checking in. I'm back from leave now. I'll be looking at this issue specifically tomorrow.

So get back to you soon :) 
James

**Comment by Psy-Fer** [comment] 2024-01-16 03:42
Hello,

I have been able to reproduce this issue.

When calling, you are using the `--call_mods` flag. This flag should only be used in conjunction with a model that calls modified bases, for example `--config dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_hac.cfg --call_mods`

The `rna_rp4_130bps_sup.cfg` model isn't calling any mods, just basecalling the RNA004 data.
Please remove the `--call_mods` flag from your command and try again.

Let me know if you run into any more issues.
James

**Comment by kir1to455** [comment] 2024-01-16 04:04
Hi, I found that https://github.com/nanoporetech/dorado with rna004_130bps_sup@v3.0.1 can call mods with m6A_DRACH.
![image](https://github.com/Psy-Fer/buttery-eel/assets/87375686/ddb8ffe5-28b6-48e5-8a6d-d9b1b2f072a2)
And in my dorado-ont-server data folder, I can only see the following RNA model.
![image](https://github.com/Psy-Fer/buttery-eel/assets/87375686/8bb7c94e-22e0-461f-bee1-87cee5cf49b8)
Is it because nanoporetech did not update it? 
My dorado-ont-server version is v7.2.13, the latest.

Thanks for your reply!
Kirito

**Comment by Psy-Fer** [comment] 2024-01-16 04:13
Hey,

Oh interesting! None of that was in any of the Change logs they wrote up.
Anyway, let me have a closer look and see what I can do.

I'll get back to you.

James

**Comment by Psy-Fer** [comment] 2024-01-16 04:43
Ahh yes indeed I can't seem to get it to call mods through my debug methods.

I am following up with ONT to see if the mod calling with this model has actually made its way over to the dorado-server yet.

I'll let you know when they get back to me :) 

James

**Comment by Psy-Fer** [comment] 2024-01-16 10:18
Hey,

Okay so ONT got back to me. Dorado server version 7.2.13 does NOT have support for m6A_DRACH yet.
It will be coming "soon" in a new release, but I'll have to do some modifications to how buttery-eel works to make it work.

So that means support will released in this order
1. new dorado server 7.3.* released
2. New buttery-eel 0.5.0 released to support it

For now, might be best to convert your data to pod5 with blue-crab and basecall your RNA with the latest standalone dorado.

Cheers,
James

**Comment by hasindu2008** [comment] 2024-01-16 11:37
@kir1to455 From which version of stand-alone Dorado is this m6A supported do you know? 
I am wondering if the version of slow5-dorado supports this https://github.com/hiruna72/slow5-dorado/releases/tag/v0.3.4.

If you are interested, we can also look into providing a newer version of slow5-dorado, while this becomes available in buttery-eel.

**Comment by kir1to455** [comment] 2024-01-16 11:49
Thanks for @Psy-Fer quick reply!
Looking forward to the new New buttery-eel 0.5.0 released!
@hasindu2008 Hi, I have used dorado version 0.5.1(the latest) to call RNA methylation(m6A@DRACH).
But its speed is incredibly slow. I think the slow5 format may be much better than pod5 or fast5, and the speed of the buttery-eel will also be faster than Dorado.

Best wishes,
Kirito

**Comment by Psy-Fer** [comment] 2024-08-16 03:23
Hey,

So following this up since the release of 7.4.12 dorado server, they have this change in their release notes

```
Added support for the rna004_130bps_sup@v3.0.1_m6A_DRACH@v1 modified base RNA model through the rna_rp4_130bps_modebases_m6a_drach_sup.cfg config file.
```

So I'm adding this to my list of things to check works for v0.5.0 of buttery-eel

James

**Comment by Psy-Fer** [comment] 2024-09-07 09:05
This should now work with
https://github.com/Psy-Fer/buttery-eel/releases/tag/v0.5.0

Cheers,
James

**Closed as completed by Psy-Fer** 2024-09-07 09:05 UTC
Labels: enhancement
