### ISSUE TITLE
m6A modification and extract features

### ISSUE THREAD

**Issue by hanyishui0612** [Psy-Fer/buttery-eel#59] opened 2024-10-21 01:29 UTC
I performed buttery-eel basecalling on the slow5 file and got the fastq file. I want to detect m6A modification. Can I extract information from the slow5 file and the resulting fastq file to build a model that detects m6A modification?

**Comment by Psy-Fer** [comment] 2024-10-21 02:56
Have you tried the `rna_rp4_130bps_modbases_m6a_drach_sup.cfg` model available in dorado-server 7.4.12?

I am still doing some testing of this myself to ensure things are working well, as this is new from nanopore.
However that will call m6a modifications.

If you wish to use a tool from the research community, you can try m6anet (https://github.com/GoekeLab/m6anet)

If you are looking to build your own model, I would perhaps direct you to the paper about m6anet. (https://www.nature.com/articles/s41592-022-01666-1)

Let me know if you have any questions.

James

**Comment by hanyishui0612** [comment] 2024-10-21 03:05
Hi,thank you for your reply!
I have not tried the rna_rp4_130bps_modbases_m6a_drach_sup.cfg model available in dorado-server 7.4.12.
I have used m6Anet before and read the corresponding literature. I want to build a model based on the slow5 file.
Annother question:I compared the fastq files generated by buttery-eel and guppy to the reference genome files and found that the comparison results were slightly different.I guess the guppy version in buttery-eel is inconsistent with the guppy version used. I guess this may be the reason.If there is a slight difference between the two comparison results, will it affect the subsequent analysis results?

**Comment by Psy-Fer** [comment] 2024-10-21 03:10
Hey,

How did you test the comparison?

We run checks for consistency between basecalls made by guppy and those made by buttery-eel running the same guppy version, or dorado-server and buttery-eel dorado-server version. Could you give me more details on the differences you observed?

Thanks
James

**Comment by hanyishui0612** [comment] 2024-10-21 03:17
Sorry,My software versions are inconsistent.And now running the same version of basecalling.For my comparison,I aligned the fastq files to the reference genome using minimap2.Then compare the resulting files. 
For example:
` 3c3
< 09169bc1-43af-4703-8cf4-2e69296f8760	1662	0	1659	+	1	30427671	3644	5898	1553	2304	60	mm:i:56	io:i:30	in:i:50	do:i:54	dn:i:645	AS:i:1616
---
> 09169bc1-43af-4703-8cf4-2e69296f8760	1661	0	1657	+	1	30427671	3644	5898	1552	2302	60	mm:i:57	io:i:29	in:i:48	do:i:54	dn:i:645	AS:i:1618    `

**Comment by Psy-Fer** [comment] 2024-10-21 03:51
hey,

Yea so i would advise running again with the same version and checking. Also noting that if you run the basecallers on different GPUs or even the same GPU with a change in the chunk size, you will get different results (this is not related to buttery-eel, this happens with ONT basecallers in general)

James

**Comment by hanyishui0612** [comment] 2024-10-21 03:54
thank you .I keep calling all GPUs. thank you for your reply

**Comment by hanyishui0612** [comment] 2024-10-22 02:35
Hi，I got the result.I ran the 6.4.2 guppy version of buttery-eel, and the results were aligned to the reference genome (the same operation was performed for the 6.4.2 guppy version).I converted the sam file I got into a paf file.The two resulting PAF files have only 8% overlap.（Previously, different versions of guppy could get 60% intersection）.Below are some different reads:
![github](https://github.com/user-attachments/assets/af0b9522-675a-46d4-8fff-4cccb2488a5a)
How should I do ?Will this affect subsequent analysis?Looking forward for your reply :)

**Comment by Psy-Fer** [comment] 2024-10-22 02:43
Happy to look into this. Please let me know the following information:

Which version of buttery-eel did you run?
What were the commands used?
What was your minimap2 command?

Thanks
James

**Comment by hanyishui0612** [comment] 2024-10-22 02:56
> Happy to look into this. Please let me know the following information:
> 
> Which version of buttery-eel did you run? 0.5.2
 What were the commands used?
buttery-eel  -g ./ont-guppy/bin/  --config rna_r9.4.1_70bps_hac.cfg --device 'cuda:all' -i  ./signals_time.blow5 -o DRS-WT-rep1.fastq --port 5566  --use_tcp 

./guppy_basecaller -i   ./fast5_pass/ -s guppy_output  -c rna_r9.4.1_70bps_hac.cfg  --num_callers 6 --gpu_runners_per_device 'cuda:all'
 What was your minimap2 command?
minimap2 -ax  map-ont --MD -t 10 ./Ath/Genome/Ath.fa.mmi  ./guppy_pass.fastq >DRS-WT-rep1_guppy.sam
> 
> Thanks James

**Comment by Psy-Fer** [comment] 2024-10-22 03:10
And is that the minimap2 command for both?

**Comment by hanyishui0612** [comment] 2024-10-22 03:11
> And is that the minimap2 command for both?

YES

**Comment by Psy-Fer** [comment] 2024-10-22 03:14
Could you convert just 1 of the fast5 files to blow5, and share both of them with me so I can have a look?

**Comment by hanyishui0612** [comment] 2024-10-22 03:33
I convert just 1 of the fast5 files to blow5:
DRS-WT-rep1 /home/ashui/Software/slow5tools-v1.3.0/slow5tools f2s FAO92801_pass_79593b9a_9.fast5  -d  ./FAO92801_pass_79593b9a_9.blow5  -p 10
fast5  Upload does not support fast5 file format  and slow5 file format

**Comment by hanyishui0612** [comment] 2024-10-22 03:33
Can you give me your e-mail?

**Comment by Psy-Fer** [comment] 2024-10-22 03:36
j.ferguson@garvan.org.au

**Comment by hanyishui0612** [comment] 2024-10-22 03:53
I have sent it to you:)

**Comment by Psy-Fer** [comment] 2024-10-22 05:25
Thanks. Downloading them now. I'll get back to you when I've had a chance to test them.

**Comment by Psy-Fer** [comment] 2024-10-24 03:52
Hey, could you send me a link of where to download the Ath reference file you are using?

Thanks

**Comment by hanyishui0612** [comment] 2024-10-24 03:54
It is  TARI10.thank you for your reply  

---- Replied Message ----
| From | James ***@***.***> |
| Date | 10/24/2024 11:53 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [Psy-Fer/buttery-eel] m6A modification and extract features (Issue #59) |

Hey, could you send me a link of where to download the Ath reference file you are using?

Thanks

**Comment by Psy-Fer** [comment] 2024-10-24 04:52
Hmm, okay so here is what I did

buttery-eel with guppy v6.4.2
```
buttery-eel -g ~/Downloads/ont-guppy-6.4.2/bin --config rna_r9.4.1_70bps_hac.cfg --device 'cuda:all' -i ./FAO92801_pass_79593b9a_9.blow5 -o b5_out_6.4.2.fastq --port auto --use_tcp
```

guppy-basecaller v6.4.2
```
~/Downloads/ont-guppy-6.4.2/bin/guppy_basecaller -i ./ -s guppy_output -c rna_r9.4.1_70bps_hac.cfg --num_callers 4 -x 'cuda:all'
```
the input `-i` was just that fast5 file you sent me
I moved the fastq output to `f5_out_6.4.2.fastq`

I then ran minimap2 on both, going directly to paf
```
minimap2 -x map-ont --MD -t 10 ./TAIR10_chr_all.fas.gz ./b5_out_6.4.2.fastq > b5_6.4.2.paf
minimap2 -x map-ont --MD -t 10 ./TAIR10_chr_all.fas.gz ./f5_out_6.4.2.fastq > f5_6.4.2.paf
```

I then sorted these files by read-id
```
cat b5_6.4.2.paf | sort > b5_6.4.2.sorted.paf
cat f5_6.4.2.paf | sort > f5_6.4.2.sorted.paf
```

I then ran a diff on those sorted files
```
diff b5_6.4.2.sorted.paf f5_6.4.2.sorted.paf
```
and it found no differences.

So in short, I have not been able to reproduce this issue.

I ran all of this on my laptop with the files you sent me using a single GPU, (GeForce RTX 3050 Ti Mobile).
If you mix GPUs then it will give you different results, so please only use 1 GPU for the calling.

Could you please try running the same commands as me on these example files you sent me?

I used this genome for the alignment
https://www.arabidopsis.org/download/list?dir=Genes%2FTAIR10_genome_release%2FTAIR10_chromosome_files
(the last one in the list)

Please give it a try and get back to me.

Cheers,
James

**Comment by hanyishui0612** [comment] 2024-10-24 07:16
Thank you for your reply.My computer only have a single GPU  and the the result of basecalling (fastq) is different. I don't know what causes this

**Comment by Psy-Fer** [comment] 2024-10-24 07:38
What GPU do you have?

and are you running the commands as I did above? I did notice your guppy command that you set to me was not quite right

you had
```
./guppy_basecaller -i ./fast5_pass/ -s guppy_output -c rna_r9.4.1_70bps_hac.cfg --num_callers 6 --gpu_runners_per_device 'cuda:all'
```

mine is
```
guppy_basecaller -i ./ -s guppy_output -c rna_r9.4.1_70bps_hac.cfg --num_callers 4 -x 'cuda:all'
```

also in the minimap2 command, dropping -a also drops the cigar string calculations so the alignment method is actually different. So having both go directly to paf helps normalise any alignment differences.

**Comment by hanyishui0612** [comment] 2024-10-25 09:02
> What GPU do you have?
> 
> and are you running the commands as I did above? I did notice your guppy command that you set to me was not quite right
> 
> you had
> 
> ```
> ./guppy_basecaller -i ./fast5_pass/ -s guppy_output -c rna_r9.4.1_70bps_hac.cfg --num_callers 6 --gpu_runners_per_device 'cuda:all'
> ```
> 
> mine is
> 
> ```
> guppy_basecaller -i ./ -s guppy_output -c rna_r9.4.1_70bps_hac.cfg --num_callers 4 -x 'cuda:all'
> ```
> 
> also in the minimap2 command, dropping -a also drops the cigar string calculations so the alignment method is actually different. So having both go directly to paf helps normalise any alignment differences.

Thank you for your reply!I followed the command you gave and re-ran it, and the results were the same. But my purpose is to compare whether there is any difference in the specific alignment results of the two software to the reference genome (if there is a difference, can the difference be ignored).In such a scenario, it should be inappropriate to ignore the -a parameter in the minimap2 comparison step. What do you think? Looking forward to your reply

**Comment by hasindu2008** [comment] 2024-10-25 09:34
@hanyishui0612 

I do not understand this part - "But my purpose is to compare whether there is any difference in the specific alignment results of the two software to the reference genome (if there is a difference, can the difference be ignored)." 

Are you using `-a` for one of the FASTQs and without `-a` on the other FASTQ?
If so, the results will be indeed different.

Or else, are you saying that when you run minimap2 with `-a` on both FASTQ, convert both the SAM to PAF, then compare the two PAF, they are different? If so, Could you provide the exact list of commands (like @Psy-Fer  provided in his explanation above) so that we can just copy-paste the commands and reproduce this difference on our side?

**Comment by Psy-Fer** [comment] 2024-10-25 11:30
The alignment algorithms are different if you run minimap with or without cigar strings. therefore they are not comparable.

If you want to have cigar alignment in paf, add the `-c` flag

**Comment by hanyishui0612** [comment] 2024-10-25 12:06
Hi,
Thank you for your reply.You mean，run 
```python
 minimap2 -ax map-ont --MD  -t 10 ../genomes/Ath/Genome/Ath.fa  ./f5.fastq  >./test_guppy.sam
```
The alignment algorithms are different.Can you tell me why?I want to have cigar alignment in paf, add the -c flag,like this
```python
 minimap2  -cx map-ont --MD  -t 10 ../genomes/Ath/Genome/Ath.fa  ./f5.fastq  >./test_guppy.paf
```
Is that true? Looking forward to your reply.

**Comment by Psy-Fer** [comment] 2024-10-25 12:58
Hello, 

I think so yes, according to my memory of how Minimap2 works. I won't be able to test this till Tuesday.

However you could just run the commands and compare the output.

James

**Comment by hanyishui0612** [comment] 2024-10-27 09:21
> Hello,
> 
> I think so yes, according to my memory of how Minimap2 works. I won't be able to test this till Tuesday.
> 
> However you could just run the commands and compare the output.
> 
> James



> The alignment algorithms are different if you run minimap with or without cigar strings. therefore they are not comparable.
> 
> If you want to have cigar alignment in paf, add the `-c` flag

I want to get more detailed comparison information, so I think adding the cigar string is more appropriate.(The ultimate goal is to see if there is a big gap between the fastq comparison obtained by buttery-eel and guppy and the reference genome file. If there is no big gap, we can then extract relevant features from the file.)There are  differences between directly obtaining files in paf format through minimap2 and converting bam files into paf format files.Of these two methods, I think the paf file obtained through the bam file is clearer. What do you think?
Here are my code:
‘’‘python
 buttery-eel -g  ./ont-guppy/bin  --config rna_r9.4.1_70bps_hac.cfg --device 'cuda:all' -i ./signals_time.blow5  -o ./test/b5.fastq --port auto --use_tcp
 ./ont-guppy/bin/guppy_basecaller -i ./fast5_pass  -s ./test/guppy_output -c rna_r9.4.1_70bps_hac.cfg --num_callers 4 -x 'cuda:all'
  cat *.fastq >guppy_pass.fastq
 mv guppy_pass.fastq  f5.fastq 
 minimap2 -ax map-ont --MD  -t 10 ../genomes/Ath/Genome/Ath.fa  ./f5.fastq  >./test_guppy.sam
 minimap2 -ax map-ont --MD  -t 10 ../genomes/Ath/Genome/Ath.fa  ./b5.fastq  >./test_buttery-eel.sam
samtools view -bh -@ 10 ./test_guppy.sam >./test_guppy.bam
samtools view -bh -@ 10 ./test_buttery-eel.sam >./test_.bam
 htsbox samview -p test_guppy.bam >test_guppy.paf
 htsbox samview -p test_buttery.bam >test_buttery.paf
’‘’

**Comment by hanyishui0612** [comment] 2024-10-27 09:24
I want to get more detailed comparison information, so I think adding the cigar string is more appropriate.(The ultimate goal is to see if there is a big gap between the fastq comparison obtained by buttery-eel and guppy and the reference genome file. If there is no big gap, we can then extract relevant features from the file.)There are differences between directly obtaining files in paf format through minimap2 and converting bam files into paf format files.Of these two methods, I think the paf file obtained through the bam file is clearer. What do you think?
Here are my code:
```python
buttery-eel -g ./ont-guppy/bin --config rna_r9.4.1_70bps_hac.cfg --device 'cuda:all' -i ./signals_time.blow5 -o ./test/b5.fastq --port auto --use_tcp
./ont-guppy/bin/guppy_basecaller -i ./fast5_pass -s ./test/guppy_output -c rna_r9.4.1_70bps_hac.cfg --num_callers 4 -x 'cuda:all'
cat *.fastq >guppy_pass.fastq
mv guppy_pass.fastq f5.fastq
minimap2 -ax map-ont --MD -t 10 ../genomes/Ath/Genome/Ath.fa ./f5.fastq >./test_guppy.sam
minimap2 -ax map-ont --MD -t 10 ../genomes/Ath/Genome/Ath.fa ./b5.fastq >./test_buttery-eel.sam
samtools view -bh -@ 10 ./test_guppy.sam >./test_guppy.bam
samtools view -bh -@ 10 ./test_buttery-eel.sam >./test_.bam
htsbox samview -p test_guppy.bam >test_guppy.paf
htsbox samview -p test_buttery.bam >test_buttery.paf
```

**Comment by Psy-Fer** [comment] 2024-10-27 11:33
And are they different?

**Comment by hanyishui0612** [comment] 2024-10-27 11:37
yes.


---- Replied Message ----
| From | James ***@***.***> |
| Date | 10/27/2024 19:33 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [Psy-Fer/buttery-eel] m6A modification and extract features (Issue #59) |

And are they different?

**Comment by Psy-Fer** [comment] 2024-10-27 11:43
How?

**Comment by hanyishui0612** [comment] 2024-10-28 09:50
Thank you for your reply.I run again
```python
buttery-eel -g ./ont-guppy/bin --config rna_r9.4.1_70bps_hac.cfg --device 'cuda:all' -i ./signals_time.blow5 -o ./test/b5.fastq --port auto --use_tcp
./ont-guppy/bin/guppy_basecaller -i ./fast5_pass -s ./test/guppy_output -c rna_r9.4.1_70bps_hac.cfg --num_callers 4 -x 'cuda:all'
cat *.fastq >guppy_pass.fastq
mv guppy_pass.fastq f5.fastq
minimap2 -ax map-ont --MD  -t 10 ../genomes/Ath/Genome/Ath.fa  ./b5.fastq  >./test_buttery-eel.sam

 minimap2 -ax map-ont --MD  -t 10 ../genomes/Ath/Genome/Ath.fa  ./f5.fastq  >./test_guppy.sam

samtools view -@ 10 -F 4 -h  ./test_buttery-eel.sam  -o  ./test_buttery-eel_align.sam
samtools view -@ 10 -F 4 -h  ./test_guppy.sam  -o  ./test_guppy_align.sam

 sam->bam

 samtools view -@ 10 -S -b test_guppy_align.sam -o test_guppy_align.bam
samtools view -@ 10 -S -b test_buttery-eel_align.sam -o test_buttery-eel_align.bam

 htsbox samview -p test_buttery-eel_align.bam >test_buttery-eel_align.paf
 htsbox samview -p test_guppy_align.bam >test_guppy_align.paf

 cat ./test_buttery-eel_align.paf  |sort >./test_buttery_align_sort.paf
 cat ./test_guppy_align.paf |sort >./test_guppy_align_sort.paf

 diff ./test_buttery_align_sort.paf ./test_guppy_align_sort.paf  >./diff.txt

```
In the minimap2 step, I retain the -a parameter mainly to retain the cigar operation(The cigar string contains more detailed comparison information).And use samtools to remove reads that are not mapped to the reference genome.
Only more than 100 reads are inconsistent, and the diff.txt is only 28k.I think this difference can be ignored, what do you think?

**Comment by Psy-Fer** [comment] 2024-10-31 03:05
Could you get the read-ids of the reads that are inconsistent, and extract them into a blow5 file using `slow5tools get` and send it to me?

Then I can look at them with my tools to see what is happening.

But yes, if it is only 100 reads, it is pretty negligible.

Thanks
James

**Comment by hasindu2008** [comment] 2024-10-31 12:55
I  think it could be the CIGAR string. There could be a tiny fraction of bases that are different here and there due to differences in guppy_basecaller and guppy_basecall server and this would be reflected in the CIGAR string.

**Comment by Psy-Fer** [comment] 2024-10-31 13:12
Indeed. Guppy wasn't always consistent between the stand-alone basecaller and the server/client software.
It would spit out random stuff in some cases too.

This got better with newer versions and now dorado-server.

**Comment by hasindu2008** [comment] 2024-10-31 13:24
Even Guppy standalone  is not consistent - if you run the same Guppy standalone version on two models of GPUs, it can produce slightly different results. Same applies to Dorado. 

The identity scores compared when Dorado standalone is run on a Tesla V100 GPU vs a L4 GPU:
![image](https://github.com/user-attachments/assets/4c33c432-323c-40a9-a0db-61862ad544f3)

CPU vs GPU:
![image](https://github.com/user-attachments/assets/7350edeb-a516-4dd9-af92-469ac157c915)

V100 vs A100:
![image](https://github.com/user-attachments/assets/92155788-c4c8-4042-ad50-40f6f9beb2ca)

V100 vs H100:
![image](https://github.com/user-attachments/assets/fd987c48-3990-47b7-acda-4da2ed1af2fc)

V100 vs Mac mini
![image](https://github.com/user-attachments/assets/a5d51e62-2164-4e18-8fa4-19558965991f)

**Closed as completed** 2024-12-10 04:03 UTC
